-- MySQL Script generated by MySQL Workbench
-- Tue Sep 15 22:00:33 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema dbcompraensalta
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema dbcompraensalta
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `dbcompraensalta` DEFAULT CHARACTER SET utf8 ;
USE `dbcompraensalta` ;

-- -----------------------------------------------------
-- Table `dbcompraensalta`.`tipoauditoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbcompraensalta`.`tipoauditoria` (
  `iIdTipoAuditoria` INT(11) NOT NULL AUTO_INCREMENT,
  `sDescripcion` VARCHAR(100) NULL DEFAULT NULL,
  `sAbreviatura` VARCHAR(50) NULL DEFAULT NULL,
  PRIMARY KEY (`iIdTipoAuditoria`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `dbcompraensalta`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbcompraensalta`.`usuarios` (
  `iIdUsuarios` INT(11) NOT NULL AUTO_INCREMENT,
  `sLogin` VARCHAR(65) NOT NULL,
  `sClave` VARCHAR(64) NOT NULL,
  `sSalt` VARCHAR(64) NULL DEFAULT NULL,
  `sNombre` VARCHAR(100) NOT NULL,
  `sApellido` VARCHAR(100) NOT NULL,
  `sEmail` VARCHAR(100) NOT NULL,
  `sDomicilio` VARCHAR(100) NULL DEFAULT NULL,
  `iDNI` INT(11) NULL DEFAULT NULL,
  `sUltimoIP` VARCHAR(100) NULL DEFAULT NULL,
  `dFechaAlta` DATETIME NULL DEFAULT NULL,
  `dUltimaFechaLogin` DATETIME NULL DEFAULT NULL,
  `bEliminado` TINYINT(1) NULL DEFAULT NULL,
  PRIMARY KEY (`iIdUsuarios`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `dbcompraensalta`.`auditorias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbcompraensalta`.`auditorias` (
  `iIdAuditorias` INT(11) NOT NULL AUTO_INCREMENT,
  `dFecha` DATETIME NULL DEFAULT NULL,
  `sDescripcion` VARCHAR(400) NULL DEFAULT NULL,
  `Usuarios_iIdUsuarios` INT(11) NOT NULL,
  `TipoAuditoria_iIdTipoAuditoria` INT(11) NOT NULL,
  PRIMARY KEY (`iIdAuditorias`),
  CONSTRAINT `fk_Auditorias_TipoAuditoria1`
    FOREIGN KEY (`TipoAuditoria_iIdTipoAuditoria`)
    REFERENCES `dbcompraensalta`.`tipoauditoria` (`iIdTipoAuditoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Auditorias_Usuarios1`
    FOREIGN KEY (`Usuarios_iIdUsuarios`)
    REFERENCES `dbcompraensalta`.`usuarios` (`iIdUsuarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

-- CREATE INDEX `fk_Auditorias_Usuarios1_idx` ON `dbcompraensalta`.`auditorias` (`Usuarios_iIdUsuarios` ASC) VISIBLE;

-- CREATE INDEX `fk_Auditorias_TipoAuditoria1_idx` ON `dbcompraensalta`.`auditorias` (`TipoAuditoria_iIdTipoAuditoria` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `dbcompraensalta`.`productos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbcompraensalta`.`productos` (
  `iIdProductos` INT(11) NOT NULL AUTO_INCREMENT,
  `sCodigo` VARCHAR(50) NULL DEFAULT NULL,
  `sNombre` VARCHAR(100) NULL DEFAULT NULL,
  `sDescripcion` VARCHAR(400) NULL DEFAULT NULL,
  `iStock` INT(11) NULL DEFAULT NULL,
  `iStockMinimo` INT(11) NULL DEFAULT NULL,
  `fPrecio` DECIMAL(18,2) NULL DEFAULT NULL,
  `dFecha` DATETIME NULL DEFAULT NULL,
  `iIdImagenPrincipal` INT(11) NULL DEFAULT NULL,
  `bPublicado` TINYINT(1) NULL DEFAULT NULL,
  `bEliminado` TINYINT(1) NULL DEFAULT NULL,
  PRIMARY KEY (`iIdProductos`))
ENGINE = InnoDB
AUTO_INCREMENT = 31
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `dbcompraensalta`.`carritosdecompras`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbcompraensalta`.`carritosdecompras` (
  `iIdCarritosdeCompras` INT(11) NOT NULL AUTO_INCREMENT,
  `iCantidad` INT(11) NULL DEFAULT NULL,
  `dUltimaFecha` DATETIME NULL DEFAULT NULL,
  `iIdUsuarios` INT(11) NOT NULL,
  `iIdProductos` INT(11) NOT NULL,
  PRIMARY KEY (`iIdCarritosdeCompras`),
  CONSTRAINT `fk_CarritosdeCompras_Productos1`
    FOREIGN KEY (`iIdProductos`)
    REFERENCES `dbcompraensalta`.`productos` (`iIdProductos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_CarritosdeCompras_Usuarios1`
    FOREIGN KEY (`iIdUsuarios`)
    REFERENCES `dbcompraensalta`.`usuarios` (`iIdUsuarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

-- CREATE INDEX `fk_CarritosdeCompras_Usuarios1_idx` ON `dbcompraensalta`.`carritosdecompras` (`iIdUsuarios` ASC) VISIBLE;

-- CREATE INDEX `fk_CarritosdeCompras_Productos1_idx` ON `dbcompraensalta`.`carritosdecompras` (`iIdProductos` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `dbcompraensalta`.`categorias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbcompraensalta`.`categorias` (
  `iIdCategorias` INT(11) NOT NULL AUTO_INCREMENT,
  `sNombre` VARCHAR(100) NULL DEFAULT NULL,
  `sDescripcion` VARCHAR(400) NULL DEFAULT NULL,
  `dFechaAlta` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`iIdCategorias`))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `dbcompraensalta`.`comentarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbcompraensalta`.`comentarios` (
  `iIdComentarios` INT(11) NOT NULL AUTO_INCREMENT,
  `sTitulo` VARCHAR(100) NULL DEFAULT NULL,
  `sTexto` VARCHAR(400) NULL DEFAULT NULL,
  `Productos_iIdProductos` INT(11) NOT NULL,
  `Usuarios_iIdUsuarios` INT(11) NOT NULL,
  PRIMARY KEY (`iIdComentarios`),
  CONSTRAINT `fk_Comentarios_Productos1`
    FOREIGN KEY (`Productos_iIdProductos`)
    REFERENCES `dbcompraensalta`.`productos` (`iIdProductos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Comentarios_Usuarios1`
    FOREIGN KEY (`Usuarios_iIdUsuarios`)
    REFERENCES `dbcompraensalta`.`usuarios` (`iIdUsuarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

-- CREATE INDEX `fk_Comentarios_Productos1_idx` ON `dbcompraensalta`.`comentarios` (`Productos_iIdProductos` ASC) VISIBLE;

-- CREATE INDEX `fk_Comentarios_Usuarios1_idx` ON `dbcompraensalta`.`comentarios` (`Usuarios_iIdUsuarios` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `dbcompraensalta`.`imagenes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbcompraensalta`.`imagenes` (
  `iIdImagenes` INT(11) NOT NULL AUTO_INCREMENT,
  `sNombreArchivo` VARCHAR(100) NULL DEFAULT NULL,
  `sTipoExtension` VARCHAR(50) NULL DEFAULT NULL,
  `sPath` VARCHAR(400) NULL DEFAULT NULL,
  `bEliminado` TINYINT(1) NULL DEFAULT NULL,
  PRIMARY KEY (`iIdImagenes`))
ENGINE = InnoDB
AUTO_INCREMENT = 73
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `dbcompraensalta`.`marcas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbcompraensalta`.`marcas` (
  `iIdMarcas` INT(11) NOT NULL AUTO_INCREMENT,
  `sNombre` VARCHAR(100) NULL DEFAULT NULL,
  `sDescripcion` VARCHAR(400) NULL DEFAULT NULL,
  `iOrden` INT(11) NULL DEFAULT NULL,
  `bPublicado` TINYINT(1) NULL DEFAULT NULL,
  `bEliminado` TINYINT(1) NULL DEFAULT NULL,
  `dFecha` DATETIME NULL DEFAULT NULL,
  `Imagenes_iIdImagenes` INT(11) NOT NULL,
  PRIMARY KEY (`iIdMarcas`),
  CONSTRAINT `fk_Marcas_Imagenes1`
    FOREIGN KEY (`Imagenes_iIdImagenes`)
    REFERENCES `dbcompraensalta`.`imagenes` (`iIdImagenes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

-- CREATE INDEX `fk_Marcas_Imagenes1_idx` ON `dbcompraensalta`.`marcas` (`Imagenes_iIdImagenes` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `dbcompraensalta`.`ordenes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbcompraensalta`.`ordenes` (
  `iIdOrdenes` INT(11) NOT NULL AUTO_INCREMENT,
  `sNumero` VARCHAR(50) NULL DEFAULT NULL,
  `fTotal` DECIMAL(18,2) NULL DEFAULT NULL,
  `dFecha` DATETIME NULL DEFAULT NULL,
  `iUltimoEstadoOrden` INT(11) NULL DEFAULT NULL,
  `iUltimoEstadoPago` INT(11) NULL DEFAULT NULL,
  `iUltimoEstadoEnvio` INT(11) NULL DEFAULT NULL,
  `Usuarios_iIdUsuarios` INT(11) NOT NULL,
  PRIMARY KEY (`iIdOrdenes`),
  CONSTRAINT `fk_Ordenes_Usuarios1`
    FOREIGN KEY (`Usuarios_iIdUsuarios`)
    REFERENCES `dbcompraensalta`.`usuarios` (`iIdUsuarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

-- CREATE INDEX `fk_Ordenes_Usuarios1_idx` ON `dbcompraensalta`.`ordenes` (`Usuarios_iIdUsuarios` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `dbcompraensalta`.`ordendetalle`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbcompraensalta`.`ordendetalle` (
  `iIdOrdenDetalle` INT(11) NOT NULL AUTO_INCREMENT,
  `iCantidad` INT(11) NULL DEFAULT NULL,
  `fPrecio` DECIMAL(18,2) NULL DEFAULT NULL,
  `Ordenes_iIdOrdenes` INT(11) NOT NULL,
  `Productos_iIdProductos` INT(11) NOT NULL,
  PRIMARY KEY (`iIdOrdenDetalle`),
  CONSTRAINT `fk_OrdenDetalle_Ordenes1`
    FOREIGN KEY (`Ordenes_iIdOrdenes`)
    REFERENCES `dbcompraensalta`.`ordenes` (`iIdOrdenes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_OrdenDetalle_Productos1`
    FOREIGN KEY (`Productos_iIdProductos`)
    REFERENCES `dbcompraensalta`.`productos` (`iIdProductos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

-- CREATE INDEX `fk_OrdenDetalle_Ordenes1_idx` ON `dbcompraensalta`.`ordendetalle` (`Ordenes_iIdOrdenes` ASC) VISIBLE;

-- CREATE INDEX `fk_OrdenDetalle_Productos1_idx` ON `dbcompraensalta`.`ordendetalle` (`Productos_iIdProductos` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `dbcompraensalta`.`ordenhistorial`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbcompraensalta`.`ordenhistorial` (
  `iIdOrdenHistorial` INT(11) NOT NULL AUTO_INCREMENT,
  `dFecha` DATETIME NULL DEFAULT NULL,
  `iTipoEstado` INT(11) NULL DEFAULT NULL,
  `iEstado` INT(11) NULL DEFAULT NULL,
  `sHistorial` VARCHAR(400) NULL DEFAULT NULL,
  `bMostrarUsuario` TINYINT(1) NULL DEFAULT NULL,
  `Ordenes_iIdOrdenes` INT(11) NOT NULL,
  PRIMARY KEY (`iIdOrdenHistorial`),
  CONSTRAINT `fk_OrdenHistorial_Ordenes1`
    FOREIGN KEY (`Ordenes_iIdOrdenes`)
    REFERENCES `dbcompraensalta`.`ordenes` (`iIdOrdenes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

-- CREATE INDEX `fk_OrdenHistorial_Ordenes1_idx` ON `dbcompraensalta`.`ordenhistorial` (`Ordenes_iIdOrdenes` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `dbcompraensalta`.`poducto_marca`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbcompraensalta`.`poducto_marca` (
  `iIdProducto_Marca` INT(11) NOT NULL AUTO_INCREMENT,
  `iOrden` INT(11) NULL DEFAULT NULL,
  `Productos_iIdProductos` INT(11) NOT NULL,
  `Marcas_iIdMarcas` INT(11) NOT NULL,
  PRIMARY KEY (`iIdProducto_Marca`),
  CONSTRAINT `fk_Poducto_Marca_Marcas1`
    FOREIGN KEY (`Marcas_iIdMarcas`)
    REFERENCES `dbcompraensalta`.`marcas` (`iIdMarcas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Poducto_Marca_Productos1`
    FOREIGN KEY (`Productos_iIdProductos`)
    REFERENCES `dbcompraensalta`.`productos` (`iIdProductos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

-- CREATE INDEX `fk_Poducto_Marca_Productos1_idx` ON `dbcompraensalta`.`poducto_marca` (`Productos_iIdProductos` ASC) VISIBLE;

-- CREATE INDEX `fk_Poducto_Marca_Marcas1_idx` ON `dbcompraensalta`.`poducto_marca` (`Marcas_iIdMarcas` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `dbcompraensalta`.`producto_categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbcompraensalta`.`producto_categoria` (
  `iIdProducto_Categoria` INT(11) NOT NULL AUTO_INCREMENT,
  `iIdCategorias` INT(11) NOT NULL,
  `iIdProductos` INT(11) NOT NULL,
  PRIMARY KEY (`iIdProducto_Categoria`),
  CONSTRAINT `fk_Producto_Categoria_Categorias1`
    FOREIGN KEY (`iIdCategorias`)
    REFERENCES `dbcompraensalta`.`categorias` (`iIdCategorias`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Producto_Categoria_Productos1`
    FOREIGN KEY (`iIdProductos`)
    REFERENCES `dbcompraensalta`.`productos` (`iIdProductos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

-- CREATE INDEX `fk_Producto_Categoria_Categorias1_idx` ON `dbcompraensalta`.`producto_categoria` (`iIdCategorias` ASC) VISIBLE;

-- CREATE INDEX `fk_Producto_Categoria_Productos1_idx` ON `dbcompraensalta`.`producto_categoria` (`iIdProductos` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `dbcompraensalta`.`producto_imagen`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbcompraensalta`.`producto_imagen` (
  `iIdProducto_Imagen` INT(11) NOT NULL AUTO_INCREMENT,
  `iOrden` INT(11) NULL DEFAULT NULL,
  `iIdProductos` INT(11) NOT NULL,
  `iIdImagenes` INT(11) NOT NULL,
  `bEliminado` TINYINT(1) NULL DEFAULT NULL,
  PRIMARY KEY (`iIdProducto_Imagen`))
ENGINE = InnoDB
AUTO_INCREMENT = 76
DEFAULT CHARACTER SET = utf8;

-- CREATE INDEX `fk_Producto_Imagen_Productos1_idx` ON `dbcompraensalta`.`producto_imagen` (`iIdProductos` ASC) VISIBLE;

-- CREATE INDEX `fk_Producto_Imagen_Imagenes1_idx` ON `dbcompraensalta`.`producto_imagen` (`iIdImagenes` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `dbcompraensalta`.`proveedores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbcompraensalta`.`proveedores` (
  `iIdProveedores` INT(11) NOT NULL AUTO_INCREMENT,
  `sRazonSocial` VARCHAR(100) NULL DEFAULT NULL,
  `sCUIT` VARCHAR(15) NULL DEFAULT NULL,
  `sDomicilio` VARCHAR(100) NULL DEFAULT NULL,
  `sTelefono` VARCHAR(50) NULL DEFAULT NULL,
  PRIMARY KEY (`iIdProveedores`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `dbcompraensalta`.`proveedor_compra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbcompraensalta`.`proveedor_compra` (
  `iIdProveedor_Compra` INT(11) NOT NULL AUTO_INCREMENT,
  `dFecha` DATETIME NULL DEFAULT NULL,
  `iStock` INT(11) NULL DEFAULT NULL,
  `fCosto` DECIMAL(18,2) NULL DEFAULT NULL,
  `Poducto_Marca_iIdProducto_Marca` INT(11) NOT NULL,
  `Proveedores_iIdProveedores` INT(11) NOT NULL,
  PRIMARY KEY (`iIdProveedor_Compra`),
  CONSTRAINT `fk_Proveedor_Compra_Poducto_Marca1`
    FOREIGN KEY (`Poducto_Marca_iIdProducto_Marca`)
    REFERENCES `dbcompraensalta`.`poducto_marca` (`iIdProducto_Marca`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Proveedor_Compra_Proveedores1`
    FOREIGN KEY (`Proveedores_iIdProveedores`)
    REFERENCES `dbcompraensalta`.`proveedores` (`iIdProveedores`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

-- CREATE INDEX `fk_Proveedor_Compra_Poducto_Marca1_idx` ON `dbcompraensalta`.`proveedor_compra` (`Poducto_Marca_iIdProducto_Marca` ASC) VISIBLE;

-- CREATE INDEX `fk_Proveedor_Compra_Proveedores1_idx` ON `dbcompraensalta`.`proveedor_compra` (`Proveedores_iIdProveedores` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
